SpiderLabs/owasp-modsecurity-crs

- rules/lfi-os-files.txt
- rules/php-config-directives.txt
- rules/php-errors.txt
- rules/php-function-names.txt
Thanks to @emphazer for reporting the problems
> fixed duplicates in data files as reported by @emphazer

- modsecurity_crs_10_setup.conf.example
- rules/RESPONSE-51-DATA-LEAKAGES-SQL.conf
This regex has been split to add more info for the user as well as fix errors with PCRE limits that were being encountered. This worked properly on my CRS distro but should be TESTED before it is pushed to prod.
> V3.0.0 dev SQL Info Leak Regex Split

- slr_rules/modsecurity_crs_46_slr_et_wordpress_attacks.conf
Regex contained a '+' following a non-quantifiable group (specifically,
the opening case-insensitive non-capture marker).
Fixes issue #259.
> Fix broken regex in 2011256

- modsecurity_crs_10_setup.conf.example
- rules/REQUEST-10-IP-REPUTATION.conf
- rules/REQUEST-11-METHOD-ENFORCEMENT.conf
- rules/REQUEST-12-DOS-PROTECTION.conf
- rules/REQUEST-13-SCANNER-DETECTION.conf
- rules/REQUEST-20-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-21-PROTOCOL-ATTACK.conf
- rules/REQUEST-30-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-31-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-32-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-33-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-41-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-42-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-43-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-49-BLOCKING-EVALUATION.conf
- rules/RESPONSE-50-DATA-LEAKAGES-IIS.conf
- rules/RESPONSE-50-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-50-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-50-DATA-LEAKAGES.conf
- rules/RESPONSE-51-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-59-BLOCKING-EVALUATION.conf
- rules/RESPONSE-80-CORRELATION.conf
This is the first pull request in a series of four pull requests bringing support for a grouping of rules in multiple paranoia levels. See https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode for details.
This has been tested by Christian Folini and Noël Zindel.
> Introducing paranoia level constructs

- rules/REQUEST-33-APPLICATION-ATTACK-PHP.conf
- util/regression-tests/manifest.yaml
Proposal to resolve issue #310
> remove PHP extension pre-check, to run PHP rules on all URLs

- rules/REQUEST-42-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-43-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-49-BLOCKING-EVALUATION.conf
Fix for #303.
Test: Search over all rule files did not reveal any further "mutli" typos.
> fixed 'mutli' typo

- modsecurity_crs_10_setup.conf.example
The reasoning behind this action is described in #372
> Update to default configurations removing 0.9 and adding HTTP/2

- modsecurity_crs_10_setup.conf.example
- rules/REQUEST-20-PROTOCOL-ENFORCEMENT.conf
* Removed Proxy-Connection and Via from restricted_headers
* Fixed severities in 920440 and 920450
* Applied t:lowercase for restricted_headers before match
* Lowercased all headers in restricted_headers; sorted headers alphabetically.
This is a PR for #365.
> Shortening restricted_headers and fixing severities in two rules

- rules/REQUEST-20-PROTOCOL-ENFORCEMENT.conf
This covers a false negative discussed in issue #370.
> Adding sibling 920311 to empty Accept header check

- rules/REQUEST-00-LOCAL-WHITELIST.conf.example
This pull adds another example and provides much more documentation on the need. We'll need to update the documentation to match as well. thanks @lifeforms !
> Adding more detail to whitelist doc as described in #319

- modsecurity_crs_10_setup.conf.example
- rules/REQUEST-12-DOS-PROTECTION.conf
See closed PR #335 and PR #359, which are being replaced by this PR.
I tried to update 359 after seeing merge conflicts, but somehow it incorporated all recent upstream changes into the PR, growing 359 immensely. Better to start over again.
Please review (and if OK: merge before new merge conflicts appear).
> DDoS rules cleanup; stricter sibling; started new PR as former one got outdated

- modsecurity_crs_10_setup.conf.example
- rules/REQUEST-900-LOCAL-WHITELIST.conf.example
- rules/REQUEST-910-IP-REPUTATION.conf
- rules/REQUEST-911-METHOD-ENFORCEMENT.conf
- rules/REQUEST-912-DOS-PROTECTION.conf
- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-949-BLOCKING-EVALUATION.conf
- rules/RESPONSE-950-DATA-LEAKAGES.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
- rules/RESPONSE-959-BLOCKING-EVALUATION.conf
- rules/RESPONSE-980-CORRELATION.conf
This is an update as listed in #416 . It is essentially the remainder of the update that changed filenames to REQUEST-9xx from REQUEST-xx
> Update filenames within files to reflex new 9xx filename structure

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Updated text to be proper english and add a reference. This is actually an IIS specific issue as they accepted full width unicode.
> Minor update to 920260

- modsecurity_crs_10_setup.conf.example
Thank you to @franbuehler who discovered the issue.
> Minor fix to #428 example rule

- INSTALL
A rather extensive rewrite of the INSTALL file for 3.x as specified in #381
> Update INSTALL file for 3.x

- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
> Fixes for some of the issues discovered by Vlad's scripts.

- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
See #457 for additional details
> A few additional minor changes insighted based on reasearch from vlad

- rules/crawlers-user-agents.data
- rules/generic-user-agents.data
- rules/scanners-user-agents.data
Attempt to split scanners by purpose as per discussion in #406 
Comment on top of each file describes the criteria for the category
TODO include files at appropriate paranoia levels
> Split scanners

- crs-setup.conf.example
- rules/REQUEST-900-LOCAL-WHITELIST.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-905-COMMON-EXCEPTIONS.conf
- rules/REQUEST-910-IP-REPUTATION.conf
- rules/REQUEST-911-METHOD-ENFORCEMENT.conf
- rules/REQUEST-912-DOS-PROTECTION.conf
- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-949-BLOCKING-EVALUATION.conf
- rules/RESPONSE-950-DATA-LEAKAGES.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
- rules/RESPONSE-959-BLOCKING-EVALUATION.conf
- rules/RESPONSE-980-CORRELATION.conf
- rules/RESPONSE-999-EXCEPTIONS.conf.example
This time I checked from top to bottom. No additional code reverts hidden in the code because I missed a merge.
> update file headers

- rules/REQUEST-901-INITIALIZATION.conf
> Fix typos in initialization default settings

- util/upgrade.py
This fixes a tiny but significant bug with the cron functionality in upgrade.py.
> Fix bug with cron option in upgrade.py

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
> 920310: exclude FP causing "Business" client, add comments

- CHANGES
- KNOWN_BUGS
Please merge quickly - and update after RC1.
Sorry for all the stuff and people I forgot.
> Overhaul of CHANGES file, new KNOWN_BUGS file

- INSTALL
> fixed path in include example in INSTALL file

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Missing quote at the end of the rule 920200
> Missing quote at the end of the rule 920201

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Missing quote at the end of the rule 920202
> Missing quote at the end of the rule 920202

- rules/REQUEST-912-DOS-PROTECTION.conf
Adds missing comma in the action list of rule #912120
> Adds missing comma in the action list of rule #912120

- rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
- rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Please read carefully. I'm sure there are still typos (I want to get this over and as I still have quite a few issues on my plate, I am a bit in a hurry).
> Rewriting the text and the examples

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
> fixing ReDoS as demonstrated by Ryan and jnazarioFastly

- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
This is a fix for the issue described in #582 Special thanks to @eff7 for the report!
> Updating placement of RemoveNulls in XSS

- INSTALL
> Added additional information to INSTALL

- CHANGES
- KNOWN_BUGS
- crs-setup.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-910-IP-REPUTATION.conf
- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-949-BLOCKING-EVALUATION.conf
This solves #514.
Implements the fix / documentation outlined in the issue.
Flag and vars have been renamed; global switch introduced.
Had to renumber a few individual rules to make room.
> Rework persistent blocking

- crs-setup.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
As discussed in issue #615. Numerical version variable.
> tx.setup_done -> tx.crs_setup_version

- CHANGES
I am not sure I really got all the Pulls. Please check.
Then I also fixed a lot of trailing spaces in the file.
You can also update branch with final PRs if they are merged.
> Prepare CHANGES for 3.0.0-rc3
