SpiderLabs/owasp-modsecurity-crs

- base_rules/modsecurity_crs_40_generic_attacks.conf
Hey. It is possible to bypass the regular expression to detect the PHP tag if short_open_tag is enabled.
Example:
<?xml_parser_create();
This can be fixed by checking for a whitespace after `xml`.
> Fixed PHP tag bypass

- base_rules/modsecurity_crs_40_generic_attacks.conf
The current regex for file injections has a bug. It checks for a word boundary before `.htaccess`, `.htpasswd`, `.htgroup` and `.www_acl`. This will not match in the desired way, because the dot is not part of `\w`. Use a lookbehind instead.
Demonstration:
* [Word boundary](https://regex101.com/r/jV4dZ1/1)
* [Lookbehind](https://regex101.com/r/qD5rE1/1)
> Fixed bug in file injection regex

- modsecurity_crs_10_setup.conf.example
- rules/REQUEST-12-DOS-PROTECTION.conf
This has static resources listed in the setup.conf as a var. Additionally it fixes a bug with t:none appearing twice in rule 981048. These issues were reported by Barry Pollard
> V3.0.0 dev with added var static resources

- modsecurity_crs_10_setup.conf.example
Firefox sync uses a request content-type of text/plain. This is not typically used by sites but is optional. Added text/plain to the list of accepted content-types as a result.
> Added text/plain to allowed content types for firefox sync

- modsecurity_crs_10_setup.conf.example
- rules/REQUEST-10-IP-REPUTATION.conf
THIS MUST BE TESTED FIRST. The goal of this is to allow users to control which IP blacklists they block. Turns out most users want to allow search bots. This configuration will allow them to configure what the blacklist blocks.
> Split out project honeypot into a number of user controllable categories

- modsecurity_crs_10_setup.conf.example
- rules/REQUEST-10-IP-REPUTATION.conf
- New empty tx.high_risk_country_codes by default
- Better documentation
- GeoIP Lookup is only performed if tx.high_risk_country_codes
- Replaced @pm operator with @within as @pm does not perform macro expansion. Rule was thus broken in thus inactive
(-> Also updated the reference manual with a note with regards to @pm macro expansion)
> Disabling default tx.high_risk_country_codes and fixing broken rule 910100

- rules/REQUEST-20-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-21-PROTOCOL-ATTACK.conf
- rules/REQUEST-31-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-42-APPLICATION-ATTACK-SQLI.conf
- rules/RESPONSE-50-DATA-LEAKAGES.conf
This is the second pull request in a series of four pull requests bringing support for a grouping of rules in multiple paranoia levels. See https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode for details.
3.0.0-rc1 rules that are confirmed for paranoia mode have been moved to level 2. This has not been tested thoroughly.
> paranoia mode phase 2 - adding base rules

- rules/REQUEST-20-PROTOCOL-ENFORCEMENT.conf
Rule 920300 (now in PL2) performs a `skipAfter:END_ACCEPT_CHECK`. However, the `END_ACCEPT_CHECK` marker has remained at the old location, above it. So, if this rule fires, we have a skipAfter loop.
This causes the bug that if paranoia level is 2 or higher, and the client sends no Accept header, the rules and files after rule 920300 are no longer processed.
This is fixed by removing skipAfter and the marker, while keeping the "empty Accept header" check at the old paranoia level.
> fix invalid skipAfter when client sends no Accept header

- base_rules/modsecurity_crs_20_protocol_violations.conf
- base_rules/modsecurity_crs_21_protocol_anomalies.conf
- rule id 960012 updated to actual HTTP protocol specifications (this version is only valid for HTTP/1.0)
- a similary rule (with rule id 960013) was added to modsecurity_crs_21_protocol_anomalies.conf with a check for request protocol HTTP/1.1 and if a Transfer-Encoding header is missing
- changes done to reduce false positives and to fix [Issue 267](https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/267)
> update for rule id 960012

- rules/lfi-os-files.data
- util/regression-tests/manifest.yaml
Add entries for common PHP web applications and frameworks to `lfi-os-files.data`.
Currently, the LFI data file contains mostly pretty long paths, which protects against false positives. I have only used bare filenames (e.g. not prefixed with slashes or path names) if the files are likely to be in the current working directory, such as `wp-config.php` (Wordpress).
> PHP additions to lfi-os-files.data

- rules/REQUEST-33-APPLICATION-ATTACK-PHP.conf
- util/regression-tests/manifest.yaml
The `php://` syntax can be used to refer to various objects, such as local files (for LFI), remote urls (for RFI), or standard input/request body. Its occurrence indicates a possible attempt to either inject PHP code or exploit a file inclusion vulnerability in a PHP web app.
> detect PHP I/O stream injection attempts

- base_rules/modsecurity_crs_30_http_policy.conf
- base_rules/modsecurity_crs_41_sql_injection_attacks.conf
- base_rules/modsecurity_crs_50_outbound.conf
Removes duplicate actions from rules, shouldn't alter rule behavior in any way.
960032: Duplicate logdata:'%{matched_var}'
981300: Duplicate nolog
970011: Duplicate capture
> Remove redundant actions from some rules

- rules/REQUEST-10-IP-REPUTATION.conf
The HttpBL rules cause "Rule processing failed." warning message if SecHttpBlKey not set.
In debug log: "Operator error: RBL httpBl called but no key defined: set SecHttpBlKey"
Skip over the HttpBL rules when the user does not use the HttpBL feature.
We can't detect whether SecHttpBlKey is set, but we can check if the user has defined HttpBL categories to block in rule 900025 (which is commented out by default).
To keep this rule simple and fast, I only check for existence of the TX:block_* variables, and don't add more conditions to check if the variables are actually set to 1 with `"!@eq 1"`.
This resolves #313 .
> skip HttpBL checks if user has not defined one of the TX:block_* variables

- rules/REQUEST-42-APPLICATION-ATTACK-SQLI.conf
This implements the resolutions found in #317:
942420:
* Move rule to paranoia level 3, limit 8.
* Add stricter sibling to level 4 (942421), limit 3.
942430:
* Changed limit to 8.
* Add stricter sibling to level 3 (942431), limit 6.
* Add stricter sibling to level 4 (942432), limit 2.
Also changed msg for all rules, indicating limit and cookie target vs. args target.
> Moving 942420 to pl3, adding stricter siblings for 942420/942430

- rules/php-config-directives.data
- util/regression-tests/manifest.yaml
File `php-config-directives.data` contains a list of PHP configuration option names. Some of these names are commonly used on PHP cgi handlers to disable PHP security features.
Some entries from the data file are relatively uninteresting from an attacker's perspective, but are prone to cause false positives. 
Rule 933120 fires when a list entry is found together with the character `=`. For example, a variable that contains `=` as well as one of the words `engine`, `from`, `precision`, would be blocked now. That's too heavy and adds little security.
Remove these FP prone entries and add some tests for the rule.
> Remove FP prone entries from php-config-directives.data

- util/regression-tests/modsecurity_crs_59_header_tagging.conf
Adds the following scores to the `X-WAF-Score` header emitted by the regression test rules. This makes it possible to analyze the partial scores when testing the CRS.
- tx.rfi_score
- tx.lfi_score
- tx.rce_score
- tx.php_injection_score
- tx.http_violation_score
- tx.session_fixation_score
Old output: `X-WAF-Score: Total=35; sqli=0; xss=5`
New output: `X-WAF-Score: Total=35; sqli=0; xss=5; rfi=0; lfi=5; rce=5; php=15; http=5; ses=0`
> Add new scores to regression test headers

- modsecurity_crs_10_setup.conf.example
In example setup, set variables in `phase:1` to ensure they are always set before CRS rules start.
Also add a little commit to explain why.
Some problems that can result from variables not being set in a timely fashion were discussed in issue #364.
> Setup: use phase:1 to ensure variables always set before CRS rules

- rules/REQUEST-10-IP-REPUTATION.conf
- rules/REQUEST-13-SCANNER-DETECTION.conf
- rules/REQUEST-30-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-31-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-32-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-33-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-43-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-49-BLOCKING-EVALUATION.conf
- rules/RESPONSE-50-DATA-LEAKAGES-IIS.conf
- rules/RESPONSE-50-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-50-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-50-DATA-LEAKAGES.conf
- rules/RESPONSE-51-DATA-LEAKAGES-SQL.conf
Specified in #383
Some small changes were made to the overall suggestion in or to maintain ease of use for automated scripts. That is retaining the prefix 'attack' in front of reputational data. Additionally I removed IP_REPUTATION/MALICIOUS_CLIENT type tagging as it was redundant and didn't really add anything in most cases.
> Update Tags to be more unified as specified in #383

- rules/REQUEST-20-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-41-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-42-APPLICATION-ATTACK-SQLI.conf
Remove tags containing URLs, as discussed in #383.
The URLs were already present in the comments, so the tags can just be deleted.
> Remove web addresses from tags

- rules/scanners-user-agents.data
Noticed that the cool [commix](https://github.com/stasinopoulos/commix) command injection tool was missing from the list of scanners. (For those currently testing with it, no fear, it has `--user-agent` and `--random-agent` options)
> scanners-user-agents: add commix

- rules/REQUEST-20-PROTOCOL-ENFORCEMENT.conf
Removed rule 920110 which is incompatible in ModSec 2.x with all platforms except Apache. This change is proposed regaurdless of the outcome of https://github.com/SpiderLabs/ModSecurity/issues/1028 as ModSecurity 2.x doesn't really support this and this rule adds very little to the ruleset as Apache will throwout the URL as part of normal operation.
Suggested in #394
> Remove rule 920110 using WEBSERVER_ERROR_LOG

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- util/regression-tests/manifest.yaml
I noticed that in rule 942100, the detectSQLi operator is only used on a limited number of variables:
```
SecRule ARGS|REQUEST_COOKIES|QUERY_STRING|REQUEST_FILENAME "@detectSQLi" \
```
This is different from almost all other rules. Most rules are using the standard:
```
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/*`
```
The problem of omitting `ARGS_NAMES` is that bare POST data goes unchecked. For example, the following payload is not passed to detectSQLi by rule 942100:
```
curl --data '1%20AND%204598%3D4189' http://foo/
```
The request only gets score 5 in paranoia level 2 because of rule 942400. It is missed in paranoia level 1.
By changing the variables for detectSQLi, the above payload is checked correctly and gets score 5 in PL1, 10 …
> Use detectSQLi operator on all standard variables

- rules/RESPONSE-980-CORRELATION.conf
In the correlation message, SQLI score was missing, and there was a typo in LFI score, so that these two scores were not displayed.
> Fix correlation rule message

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
I noticed that some SQLI scores were not matching the total scores. Seems that some rules were only incrementing the `tx.sql_injection_score` by one instead of the actual score macro. That doesn't seem correct to me.
Also, some severity tags in SQLI file were either not matching the score, or they were numeric instead of using the standard keyword.
> Fix SQLI scores not being incremented correctly

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
920160 has an issue where if the request is invalid Apache will response before phase:2 with a 400 bad request. It is looking for a content type that is non-numeric. Generally we tested this with something like content-type: 3; which has an invalid char. Phase 2 can't reach this so we shifted to phase 1.
> Fix 920160 by making it phase 1

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Finally, I have my PR for issue #323:
Here are the ranged employed for the rule and its siblings:
```
920270: PL1 : REQUEST_URI, REQUEST_HEADERS, ARGS and ARGS_NAMES
ASCII 1-255 : Full ASCII range without null character
920271: PL2 : REQUEST_URI, REQUEST_HEADERS, ARGS and ARGS_NAMES
ASCII 32-126,128-255 : Visible ASCII range 
920272: PL3 : REQUEST_URI, REQUEST_HEADERS, ARGS, ARGS_NAMES and REQUEST_BODY
ASCII 32-36,38-126 : Visible lower ASCII range without percent symbol
920273: PL4 : ARGS, ARGS_NAMES and REQUEST_BODY 
ASCII 38,44-46,48-58,61,65-90,95,97-122
& , - . 0-9 : =  A-Z _ a-z 
920274: PL4 : REQUEST_HEADERS without User-Agent, Referer and Cookie
ASCII 32,34,38,42-59,61,65-90,95,97-122
SPACE " &  * + , - . / 0-9 : = A-Z  _ a-z 	
```
Stats for 8K vanilla requests and 26K attack …
> Restricting 920270 and adding stricter siblings

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Fixes false positives from detecting `HAVING` SQLi injections (see #409).
On the dataset of 126k Reddit comments, rule 942250 (Detects MATCH AGAINST, MERGE, EXECUTE IMMEDIATE and HAVING injections) matched 2142 times (1.7%). Rule 942250 is now the biggest source of false positives on that dataset (after rule 932100 was reworked). Even a string like `I am having trouble` matches this rule.
The `HAVING...` part of rule 942250's regexp looks to be somewhat redundant, since libinjection (rule 942100) also catches HAVING syntax. All sqlmap traffic that hit this rule had score 20. So the pattern might be safe to move to higher levels.
After splitting this part off to rule 942251 at PL3, all the false positives from this rule on the Reddit dataset are gone!
> SQLi: move 'HAVING injections' to PL3

- rules/REQUEST-910-IP-REPUTATION.conf
Rule 910100 (Country block) has a WARNING severity, but it adds critical anomaly score and also adds to ip.block, so the severity should reflect this.
> fix rule 910100 severity tag to match its score

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Does exactly what it says on the tin.
Also add WARNING severity.
I didn't add attack/platform tags yet. There are many other heuristic rules in the SQLi file not having those tags, so there's not a clear template. Better to make a decision on that and fix them wholesale some time, maybe once we have some linting set up. But that's beyond this PR.
Resolves #449.
> Move 942460 (Repetitive Non-Word Characters) to PL3

- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
As discussed in #402, check `REQUEST_HEADERS:User-Agent` and `REQUEST_HEADERS:Referer` against SQLi and XSS in the libinjection rules.
Since I couldn't get libinjection to fire on some XSS in User-Agents, I took the liberty of adding the header checks to the most basic regexp-based XSS rules as well.
A visual check of these regexps leads me to believe that they won't cause much FP, especially not in UAs, and unlikely in referrers.
I've also tested with a dataset of 586 user-agents which I scraped from a site. You can find that list here if you want to test: https://lf.ms/agents.txt No FPs on those user-agents found, so I think it's safe.
> Add basic SQLi and XSS detection for User-Agent, Referer header

- modsecurity_crs_10_setup.conf.example
- rules/REQUEST-912-DOS-PROTECTION.conf
Fix for #462 , good find @lifeforms 
It turns out there were a few issues here. First the old check didn't add the '.' infront of the extension even though it was checking for it. Secondly, it added a slash at the end even after it was set in setvar to have a trailling slash, so it would never match.
If tx.1 isn't populated it acts as an empty string, which is fine -- in most cases. Here it was a problem because we'd append the / at the end which would match all the /'s normally at the end. 
```/ is within .ico/```
I updated this so that the extension is surrounded by slashes on both sides within setup.conf (this will conflict with the setup.conf fix (so we have to remember to update that or push it first and update this).
Now it checks if 
```// is in /.ico/``` which it isn't.
of course …
> Updating DOS functionality to fix extension checking

- modsecurity_crs_10_setup.conf.example
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Bugfix for issue #490.
Please merge #463 before this one.
I do not think this rule ever worked the way it was advertised in 2.2.9. It would overload TX.header_name with all header names. I have not pull this apart with creating a set of vars `TX.header_name_%{TX.0}`. This seems to work as advertised.
@csanders-git : Please use the Range / Content-Range pair for a unit test.
> fixed broken rule id 920450, explained the rule logic

- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- Session fixation detection (rule 943110) is currently structured as follows:
1) Check to see if a common session variable is in use for POST/GET args
2) Check and extract the hostname from the HTTP Referer header
3) Check to see if the Referer _starts_ with the host specified in the host header
As structured, this check could be by-passed if a malicious Referer creates a sub
domain, where the start of the domain matches the domain specified in the host header.
For example, if we have a request with the following structure:
-
stage:
input:
headers:
Host: somesite.com
Referer: "https://somesite.com.attackersite.com/"
method: GET
port: 80
uri: "/?phpsessid=asdfdasfadsads"
version: HTTP/1.0
The request will be permitted. This change suggests that the operator is changed
to an endswith() or …
> Correct session fixation detection logic

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
This pull request deals with rule 920150 as denoted in #437
> removing Rule 920150, it's redundent

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
```
#
#
#
```
See issue #393 for a detailed discussion.
> new rule: abnormal character escapes in PL4 (920460)

- crs-setup.conf.example
- util/debug/RESPONSE-981-DEBUG.conf
As discussed in #497, renaming the old regression testing server side rules to "Debug Mode".
Added a reference in the setup to `util/regression-tests/README` for people who want to do formal regression testing. We can add more comments on FTW later if needed.
> Rename legacy regression_testing to debug mode

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Implements a solution for issue #499 as discussed in that thread.
I redocumented the rule, added a reference to the exact CVE in question. The regex has also been simplified. Please check.
Curl requests to check / test the rules:
```
curl -v localhost/index.html -H "range: bytes=10-11, 20-21, 30-31, 40-41, 50-51"
curl -v localhost/index.html -H "range: bytes=10-11, 20-21, 30-31, 40-41, 50-51, 60-61"
curl -v localhost/index.pdf -H "range: bytes=10-11, 20-21, 30-31, 40-41, 50-51, 60-61"
curl -v localhost/index.pdf -H "range: bytes=10-11, 20-21, 30-31, 40-41, 50-51, 60-61, 70-71, 80-81, 90-91, 100-101, 110-11, 120-21, 130-31, 140-41, 150-51, 160-61, 170-71, 180-81, 190-91, 200-101, 210-11, 220-21, 230-31, 240-41, 250-51, 260-61, 270-71, 280-81, 290-91, 300-101, 310-311, 320-321, 330-331, …
```
> Shifted 920200 to PL2, 2 new siblings for PDFs

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
See issue #516.
The rule was built as a couple with 920330. This coupling is now torn apart as 920320 moves to PL2. The skip and the skip marker END_UA_CHECK were thus no longer necessary.
Note that I also corrected the description and fixed one of the tags in 920330. Is this really correct this way? I think the previous tag was an error.
This replaces PR #529, which got a merge conflict after the range header stuff was merged.
> Moved 920320 to PL2, new comments, removed marker END_UA_CHECK

- crs-setup.conf.example
- rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
I noticed a return of the sinqle quote rule ids. This removes them.
> fix undesired single quotes in rule ids in various files

- KNOWN_BUGS
I have seen this twice in production now.
Note that #542 seems to have a different root cause.
> Add reference to apache bug 55910 in KNOWN_BUGS

- rules/scanners-user-agents.data
Another small addition to scanners-user-agents.data
I have added the brand new BFAC scanner https://github.com/mazen160/bfac.
Mazin was kind enough to set a custom UA on my request.
w3af.org seems to be an alternative to the two w3ar listings we had so far. I wonder if we should not strip it and simply go with w3af.
> Added BFAC scanner, small improvements to scanner list

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Missing quote at the end of the rule 920200
> Missing quote at the end of the rule 920200

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Missing quote at the end of the rule 920450
> Missing quote at the end of the rule 920450

- lua/gather_ip_data.lua
Previously, execution of this script would fail with the following error in the audit log:
```
Message: Lua: Script execution failed: /usr/share/modsecurity-crs/lua/gather_ip_data.lua:8: attempt to concatenate local 'remote_addr' (a nil value)
```
using REMOTE_ADDR instead of ARGS.REMOTE_ADDR in the script fixes this issue.
> Fix script execution error

- rules/REQUEST-901-INITIALIZATION.conf
The id within the proposed exclusion rule in the comment was wrong.
> Fix rule reference in comment in sampling code

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- Add the urlDecodeUni transform operation to rules which inspect the
ARGS/ARGS_NAMES collections, which do not currently call urlDecodeUni
- This operation should be here.  Some rules were written under the assumption
that Apache/Nginx will automatically decode these collections prior to
entering Modsecurity.
- This change shouldn't impact the rule quality, but will introduce additional decoding overhead
I am creating this PR to start the discussion
Thoughts?
> Add urlDecodeUni() operation to ARG/ARGS_NAMES

- crs-setup.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
After upgrading our Apaches from 2.4.20 to 2.4.23, it seems that its string representation of the HTTP/2 protocol version has changed from `HTTP/2` to `HTTP/2.0`.
This broke the version check in CRS:
`Message: Warning. Match of "within %{tx.allowed_http_versions}" against "REQUEST_PROTOCOL" required. [file "/usr/local/etc/apache24/security2/activated_rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "1028"] [id "920430"] [rev "2"] [msg "HTTP protocol version is not allowed by policy"] [data "HTTP/2.0"] `
We have to accommodate LTS distros as well as people tracking the latest Apache. The quickest fix we can make is to just include both version strings.
> allowed_http_versions: add 'HTTP/2.0' which is used by new Apache 2

- rules/REQUEST-901-INITIALIZATION.conf
If the CRS is not configured correctly (detected by tx.setup_done), panic with error 500.
Resolves #479.
> Panic with error 500 on unconfigured CRS

- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Every attack rule must have correct tags, most importantly the `attack-` and `OWASP_CRS` tags, in order to be excluded properly with ruleRemoveTargetByTag.
Validated our rule files and added tags for the rules that were missing them.
> xss, sqli: add missing tags

- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
While testing I found that the LFI rule 930110 checking for `../` and `..\` did not use cmdLine transformation yet.
This would allow traversing the filesystem in a shell command. Due to FP, we are not so strict on all shell commands as I would have liked (e.g. `cat` and `more` commands are only blocked in limited circumstances), so it's important to watch the arguments of the shell command carefully.
Due to cmdLine transformation, these types of payloads are now caught (which weren't caught before):
```
more .'.'/passwd.txt
more .'.'\/passwd.txt
more ."./"passwd.txt
more .\./passwd.txt
.\/.\.\/passwd.txt
.\./blah
\.\./blah
^.^./foo
```
It did not have measurable effect on FP in my testing.
Windows quoting is kinda spotty for some reason, I would expect these two to match too (on Windows …
> LFI: add cmdLine transformation

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
Earlier I introduced the `platform-windows` tag to help reduce FP for people not using Windows.
I noticed that I hadn't added these tags to other existing IIS related rules.
Very minor fix.
> add platform-windows tag to platform-iis rules

- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
Thanks to @jschleus for the report. This false positive was noted in #547
> Removing overbearing use of Refer header added in 3.0.0 due to FPs

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
A CRS3 setup can give many "PCRE limits exceeded" errors on a default ModSecurity configuration, for instance on rule 942430 and related ones on lots of traffic such as WordPress.
One option could be to note this error in the known issues, and/or advocate setting higher PCRE limits. In my WordPress testing, `SecPcreMatchLimit 60000` was enough to make the errors go away, but that might be pretty high. However, we could also tweak our regexps so that they don't blow up so quickly.
This PR tries to prevent "PRCE limits exceeded" errors in some SQLI rules due to use of nested `.*` after the special char. Replaced `.*` by a search for non-special chars to limit the explosion of search trees. Now the engine can match linearly and won't need to create a lot of nodes to backtrack to earlier …
> Optimize 'special char' regexps to not exceed PCRE limits

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
The documentation should be updated to reflect the current RFC 7231 and it's wording as suggested by @mnot in #266. Thanks again!
> Documentation update for Content-Type header

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Fix issue #248 by adding word boundaries to the appropriate parts of rule 942140. I kept the regexp as-is but only added `\b` where needed.
Quick tests done show that detection stays OK but now no longer hits on longer strings containing the words.
```
test sco rules                               payload
---- --- ----------------------------------- -----------------------------------
ok   5   942140                              msysaccessobjects
ok   5   942140                              msysaces
ok   5   942140                              msysobjects
ok   5   942140                              msysqueries
ok   5   942140                              msysrelationships
ok   5   942140                              msysaccessstorage
ok   5   942140 …
```
> Fix 'msdb' false positive by adding word boundaries to 942140

- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
In my testing, rule 953120 (PHP source code leakage) often triggers as a false positive in gzipped responses, as the PHP tag `<?` is present in gzip data.
The rule contains a neat exclusion mechanism where it checks various file headers for binary file types. If one of these headers is present, the file is seen as a binary and the rule is skipped.
Add a gzip signature `\x1f\x8b\x08` to these headers.
> PHP source leakage: exclude this rule in case of gzip output

- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/restricted-files.data
Testing CRS3 I saw quite a few attempts to retrieve version control internals (`.git`), variations of WordPress config files (e.g. Google inurl:wp-config.txt), Apache config files, et cetera.
I turned detection for those probes into one restricted filename check rule. I included some from my earlier `lfi-os-files.data` additions in this rule, since those files might also be retrieved without a LFI vector if the web server is misconfigured to serve their contents (a common mistake).
I am already scanning for many of these file names for a long time with no FP, so I don't expect many FP. This may not strictly be a LFI attack so I'm open for better tagging suggestions. Also, do I have the transformations right?
> Check restricted file names

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Rule 920271 (Invalid character in request (non printable characters)) did not allow tabs and newline chars - `\t` `\r` `\n` - in ARGS when running at PL2. While there is a good case for char whitelisting, I feel it is untenable at this paranoia level.
Any form containing a newline is simply rejected in PL2, which is basically any contact form, comment form, etc... People typing spacing chars in them is terribly common. In PL2 we can't expect users to create an exclusion for every textarea.
With this change, the most frequent FP was resolved in my internal testing.
I'd preferred more discussion on the #624 but my time window is compressed so I made the PR anyway.
> byte range validation: allow tab and newline in PL2

- rules/REQUEST-921-PROTOCOL-ATTACK.conf
Resolves #623 false positives when a newline is used in GET parameter value.
I've been experimented a bit with XSS this week and consider this check more useful than I did originally. So especially since I'm the only one who complained about this FP, I am going for a compromise and move it to **PL2** instead of my proposal of PL3.
Super-complex query parameters and free-form GET forms should be sufficiently rare nowadays that my impression is that PL2 users will be able to handle the FP. If it turns out to still be a dog, we can change it in a later release.
> HTTP header injection: move ARGS_GET check to PL2 to mitigate FP
